apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
  labels:
    app: {{ template "test-api.name" . }}
    chart: {{ template "test.chart" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.app.partOf }}
    health-checks: enabled
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.grpc }}
      targetPort: {{ .Values.service.ports.grpc }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ include "test-api.name" . }}
    release: {{ .Release.Name }}
